CREATE TABLE Autor (
  idAutor INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(20) NULL,
  Apellido VARCHAR(20) NULL,
  Nacionalidad VARCHAR(45) NULL,
  PRIMARY KEY(idAutor)
);

CREATE TABLE Autor_has_Libro (
  idAutor INTEGER UNSIGNED NOT NULL,
  idLibro INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idAutor, idLibro)
);

CREATE TABLE Cliente (
  idCliente INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Apellidos VARCHAR(45) NULL,
  Nombres VARCHAR(45) NULL,
  Sexo CHAR NULL,
  Direccion VARCHAR(45) NULL,
  Telefono VARCHAR(20) NULL,
  Religion VARCHAR(20) NULL,
  Categoria VARCHAR(45) NULL,
  PRIMARY KEY(idCliente)
);

CREATE TABLE Libro (
  idLibro INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ISBN VARCHAR(45) NULL,
  Nombre VARCHAR(45) NULL,
  Editorial VARCHAR(45) NULL,
  Edicion VARCHAR(45) NULL,
  Cantidad INTEGER UNSIGNED NULL,
  PRIMARY KEY(idLibro)
);

CREATE TABLE Multa (
  idMulta INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idCliente INTEGER UNSIGNED NOT NULL,
  Precio INTEGER UNSIGNED NULL,
  Semanas INTEGER UNSIGNED NULL,
  PRIMARY KEY(idMulta)
);

CREATE TABLE Prestamo (
  idPrestamo INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idUsuario INTEGER UNSIGNED NOT NULL,
  idCliente INTEGER UNSIGNED NOT NULL,
  idLibro INTEGER UNSIGNED NOT NULL,
  Fechaprestamo DATE NULL,
  Fechadevolucion DATE NULL,
  PRIMARY KEY(idPrestamo)
);

CREATE TABLE Usuario (
  idUsuario INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(45) NULL,
  Clave VARCHAR(45) NULL,
  PRIMARY KEY(idUsuario)
);


